package com.sergio.common.exception;

public enum ErrorCode {
    BARBERSHOP_ALREADY_EXISTS,
    APPOINTMENT_CONFLICT,
    INVALID_APPOINTMENT,
    NOT_FOUND,
    VALIDATION_ERROR,
    SERVICE_ALREADY_EXISTS,
    INVALID_SERVICE,
    INTERNAL_ERROR
}
