# datasource
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.datasource.jdbc.max-size=5
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.health.enabled=false

quarkus.log.category."io.agroal".level=WARN
quarkus.log.category."org.postgresql".level=WARN

# liquibase
quarkus.liquibase.migrate-at-start=false

# hibernate
quarkus.hibernate-orm.log.format-sql=false

# cors
quarkus.http.cors.origins=${CORS_ORIGINS}

# frontend
app.frontend.url=${APP_FRONTEND_URL}

# secure cookies
app.cookies.secure=true

# redis
quarkus.redis.hosts=${REDIS_URL}
quarkus.redis.client-type=standalone
quarkus.redis.tls.enabled=true

# environment
app.env=prod

# brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}