# JSON logs
quarkus.log.console.json.enabled=true
quarkus.log.console.json.pretty-print=false
quarkus.log.console.json.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ

# Request logs
quarkus.http.access-log.enabled=false

# Datasource
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.datasource.jdbc.max-size=5
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.health.enabled=false

# Hibernate
quarkus.hibernate-orm.log.format-sql=false

# Liquibase
quarkus.liquibase.migrate-at-start=false

# Reduce noise
quarkus.log.category."io.agroal".level=WARN
quarkus.log.category."org.postgresql".level=WARN

# CORS
quarkus.http.cors.origins=${CORS_ORIGINS}

# Frontend
app.frontend.url=${APP_FRONTEND_URL}

# Backend
app.backend.url=${APP_BACKEND_URL}

# Cookies
app.cookies.secure=true

# Redis
quarkus.redis.hosts=${REDIS_URL}
quarkus.redis.client-type=standalone
quarkus.redis.tls.enabled=true

# Email
app.email.enabled=true

# Brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}

# Super Admin
admin.seed.email=${SUPER_ADMIN_EMAIL}
admin.seed.password=${SUPER_ADMIN_PASSWORD}