quarkus.log.category."com.sergio".level=DEBUG

# datasource
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/barber_booking

# hibernate
quarkus.hibernate-orm.log.format-sql=true

# CORS (FRONTEND)
quarkus.http.cors.origins=https://8efd-185-137-143-180.ngrok-free.app

# Frontend
app.frontend.url=https://8efd-185-137-143-180.ngrok-free.app

# secure cookies
app.cookies.secure=true

# Redis
quarkus.redis.hosts=redis://localhost:6379

# email
app.email.enabled=false

# brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=no-reply@trimly.com
brevo.sender.name=Trimly
