# datasource
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/barber_booking

# hibernate
quarkus.hibernate-orm.log.format-sql=true

# CORS (FRONTEND)
quarkus.http.cors.origins=*

# Frontend
app.frontend.url=https://2cac-185-137-143-180.ngrok-free.app

# Redis
quarkus.redis.hosts=redis://localhost:6379

# entorno
app.env=prod

# brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=no-reply@trimly.com
brevo.sender.name=Trimly
