# datasource
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.datasource.jdbc.max-size=5
quarkus.datasource.jdbc.min-size=0
quarkus.datasource.jdbc.initial-size=0
quarkus.datasource.health.enabled=false

quarkus.log.category."io.agroal".level=DEBUG
quarkus.log.category."org.postgresql".level=DEBUG

# liquibase
quarkus.liquibase.migrate-at-start=true

# hibernate
quarkus.hibernate-orm.log.format-sql=true

# cors
quarkus.http.cors.origins=${CORS_ORIGINS}

# frontend
app.frontend.url=${APP_FRONTEND_URL}

# redis
quarkus.redis.hosts=${REDIS_URL}

# environment
app.env=prod

# brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}