# Logging
quarkus.log.level=INFO

# JSON logs
quarkus.log.console.json.enabled=true
quarkus.log.console.json.pretty-print=false
quarkus.log.console.json.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ

# MDC fields
quarkus.log.console.json.additional-field.requestId.value=%X{requestId}
quarkus.log.console.json.additional-field.method.value=%X{method}
quarkus.log.console.json.additional-field.path.value=%X{path}

# app logs
quarkus.log.category."com.sergio".level=INFO

# request logs
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern="%r" %s %Dms

# Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true

# Expose endpoint
quarkus.micrometer.export.prometheus.path=/metrics

# JVM metrics
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.system=true

# Datasource
quarkus.datasource.db-kind=postgresql

# liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# cors
quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,x-request-id
quarkus.http.cors.access-control-allow-credentials=true

# JWT
quarkus.smallrye-jwt.enabled=true

mp.jwt.verify.issuer=barber-saas
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# PUBLIC LOGIN
quarkus.http.auth.permission.admin-login.paths=/admin/auth/login
quarkus.http.auth.permission.admin-login.policy=permit

# ADMIN ROLE POLICY
quarkus.http.auth.policy.admin-policy.roles-allowed=SUPER_ADMIN,OWNER,BARBER

# PROTECTED ADMIN API
quarkus.http.auth.permission.admin.paths=/admin/*
quarkus.http.auth.permission.admin.policy=admin-policy