quarkus.log.category."com.sergio".level=DEBUG

# datasource
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/barber_booking

# hibernate
quarkus.hibernate-orm.log.format-sql=true

# CORS (FRONTEND)
quarkus.http.cors.origins=https://7254-185-137-143-180.ngrok-free.app
#quarkus.http.cors.origins=http://localhost:3000

# Frontend
app.frontend.url=https://7254-185-137-143-180.ngrok-free.app
#app.frontend.url=http://localhost:3000

# Backend
app.backend.url=https://5d39-185-137-143-180.ngrok-free.app
#app.backend.url=http://localhost:8080

# secure cookies
app.cookies.secure=true

# Redis
quarkus.redis.hosts=redis://localhost:6379

# email
app.email.enabled=true

# brevo
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=no-reply@trimly.com
brevo.sender.name=Trimly

# superadmin credentials
admin.seed.email=admin@barber.com
admin.seed.password=123456
