# Logging
quarkus.log.level=INFO
quarkus.log.category."com.sergio".level=INFO

# Metrics
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.system=true

# Datasource
quarkus.datasource.db-kind=postgresql

# Liquibase
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,x-request-id
quarkus.http.cors.access-control-allow-credentials=true

# JWT
quarkus.smallrye-jwt.enabled=true

mp.jwt.verify.issuer=barber-saas
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

mp.jwt.token.header=Cookie
mp.jwt.token.cookie=admin_token

# PUBLIC LOGIN
quarkus.http.auth.permission.admin-login.paths=/admin/auth/login
quarkus.http.auth.permission.admin-login.policy=permit

# PUBLIC LOGOUT
quarkus.http.auth.permission.admin-logout.paths=/admin/auth/logout
quarkus.http.auth.permission.admin-logout.policy=permit

# ADMIN ROLE POLICY
quarkus.http.auth.policy.admin-policy.roles-allowed=SUPER_ADMIN,OWNER,BARBER

# PROTECTED ADMIN API
quarkus.http.auth.permission.admin.paths=/admin/*
quarkus.http.auth.permission.admin.policy=admin-policy

# OpenAI
quarkus.rest-client.openai.url=https://api.openai.com
openai.api-key=${OPENAI_API_KEY}

quarkus.rest-client.openai.connect-timeout=10000
quarkus.rest-client.openai.read-timeout=120000

quarkus.rest-client.openai.disable-default-mapper=true