name: Backend CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        run: |
          if [ -f backend/mvnw ]; then
            cd backend
            ./mvnw clean install
          else
            echo "Backend not created yet"
          fi
